### ISSUE TITLE
Clean up the base

### ISSUE THREAD

**Issue by ravijyoti3** [ravijyoti3/neeto-ui-challenge#1]

**Comment by yedhink** [comment]
@ravijyoti3 Why are you assigning me this issue when you are the one who is supposed to fix the issue? Do you need any inputs from my end?

I believe the following doc is very precise and on point. It only talks about assigning PRs. But if you feel something needs to be added in the doc so as to avoid unnecessary assignments like you have done right now, then lemme know:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/31244999/191257892-9543902c-3b3b-408a-a03e-5cf3882bb8d6.png">

PS: I will review the PR only once the PR is assigned to me.

**Comment by ravijyoti3** [comment]
I apologize @yedhink, that was a really silly error on my part. I accidentally assigned you the issue when I should have assigned you the PR.
