### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by ravijyoti3** [ravijyoti3/neeto-ui-challenge#7]

**Comment by ravijyoti3** [comment]
Deployed at https://ravijyoti3-neeto-ui.herokuapp.com/
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink  Please review.

**Comment by yedhink** [comment]
@ravijyoti3  I have provided some reviews for your closed PRs. Once you address and fix them, lemme know over here.

**Comment by ravijyoti3** [comment]
@yedhink Thanks for pointing out the issues. I have fixed the code, based on the provided feedback.

**Comment by yedhink** [comment]
@ravijyoti3 _a Fix the following issues:

- [x] Wrong validation message
<img width="455" alt="image" src="https://user-images.githubusercontent.com/31244999/192700812-5a12cc63-e970-4e21-a7fc-c1ca1d903813.png">

- [x] Description should be a text area
<img width="470" alt="image" src="https://user-images.githubusercontent.com/31244999/192700859-626c2805-69f2-4b4b-b5a3-1fec39419595.png">

- [x] Mismatch in contact pane
<img width="461" alt="image" src="https://user-images.githubusercontent.com/31244999/192700999-41c651ec-0ada-4424-b6fb-c1e32480c675.png">

Once these issues are fixed, you can mark this task as completed and go ahead with the next task.

**Comment by ravijyoti3** [comment]
@yedhink I have fixed the above issues, moving forward with the next task.
